### ISSUE TITLE
Works on LG K10 2017 (m250n) on Ubuntu 17.04, Python 2.7.13.

### ISSUE THREAD

**Issue by GijsTimmers** [Lekensteyn/lglaf#45]

**Comment by GijsTimmers** [comment]
Looks like I was a bit too fast. `lglaf` works, but the shell doesn't accept a lot of commands. `ls` works, but `cd` doesn't, for example.

**Comment by Lekensteyn** [comment]
What does "not work" mean? Did you have to use --rawshell to workaround #24?

**Comment by GijsTimmers** [comment]
Thanks for merging my PR.

By "not work", I mean that cd does not descend to any subdirectory: `cd data` fails without giving any error message. I executed `python3 lglaf.py --rawshell` but that didn't change anything. I have a feeling that it's related to my problem, though.

**Comment by Lekensteyn** [comment]
Every command runs in a separate process, so in order to make cd work you will have to run for example:

    cd dir && ls

(this is a limitation of LAF)

**Comment by GijsTimmers** [comment]
Thanks. That did the job.
