### ISSUE TITLE
restore partitions slowly

### ISSUE THREAD

**Issue by malekaltanani** [Lekensteyn/lglaf#49]
What's the solution

 dump normal But restore partitions slowly

How to edit it in order to transfer data quickly

**Comment by Lekensteyn** [comment]
This did not have a lot of details (like, what you did, etc.)

**Comment by malekaltanani** [comment]
I have been resolved the problem
Was used pypy It was faster

Thank you Peter

**Comment by steadfasterX** [comment]
@malekaltanani what do you changed to make it faster? just running partitions.py with pypy? no other changes needed?
